features_recent_button
joemasilotti/daily-log pull request #11
Opened 2024-01-24 06:19 UTC by lokeshk88

2024-01-24 06:20 UTC, lokeshk88 reviewed
All done

2024-01-24 06:22 UTC, lokeshk88 reviewed
** Add change in food , medication, exercise mvc model.Review it  **

2024-01-24 16:24 UTC, joemasilotti commented
Is this ready for review? I can’t tell from the two comments you left - they seem to provide opposite opinions!

2024-01-25 06:16 UTC, lokeshk88 commented
> Is this ready for review? I can’t tell from the two comments you left - they seem to provide opposite opinions!

yes, is ready but if u need any improper please tell

2024-01-25 08:23 UTC, lokeshk88 commented
![Screenshot from 2024-01-25 13-51-14](https://github.com/joemasilotti/daily-log/assets/142203160/de9722ed-7b3c-4c6e-9658-21cd8049365d)
![Screenshot from 2024-01-25 13-50-51](https://github.com/joemasilotti/daily-log/assets/142203160/49f370ca-96d2-4689-bb74-fdc49ce44454)
![Screenshot from 2024-01-25 13-50-43](https://github.com/joemasilotti/daily-log/assets/142203160/5fc70424-2752-4ab1-9c82-caea93aaaf4f)
![Screenshot from 2024-01-25 13-50-33](https://github.com/joemasilotti/daily-log/assets/142203160/cc11dece-f345-4b11-84a0-000dfab32f4f)
![Screenshot from 2024-01-25 13-49-34](https://github.com/joemasilotti/daily-log/assets/142203160/cfd0d038-7df0-4487-82c7-a1922c56e2c2)
![Screenshot from 2024-01-25 13-46-01](https://github.com/joemasilotti/daily-log/assets/142203160/70857256-aa08-44fc-876a-528cc2c539dc)

2024-01-25 08:32 UTC, lokeshk88 reviewed
**I review its working good.**

2024-01-25 08:33 UTC, lokeshk88 reviewed
Check it  @joemasilotti .

2024-02-28 20:41 UTC, vfonic requested changes
Looking at the code, this PR doesn't seem to be fully implemented.

2024-02-28 20:41 UTC, vfonic commented on rails/app/models/exercise_entry.rb
> +  scope :recent, -> { distinct(:name).order(created_at: :desc).limit(3) }
You have this scope three times. Maybe you can extract it into a concern? `included do scope :recent...`

Concern name could be `Recent`.

2024-02-28 20:41 UTC, vfonic commented on rails/app/models/water_entry.rb
> +  validates_presence_of :amount, :occurred_on
This seems redundant. There's already `validates :occurred_on, presence: true` and `validates :amount, presence: true`. This does the same thing, right?

2024-02-28 20:41 UTC, vfonic commented on rails/app/models/water_entry.rb
> +
Please try to keep the files tidy and not introduce irrelevant changes. You can set up your editor to automatically remove these extra new lines when you save a file.

2024-02-28 20:41 UTC, vfonic commented on rails/Procfile
> +web: bundle exec puma -C config/puma.rb -p $PORT
This change doesn't seem related with the PR.

2024-02-28 20:41 UTC, vfonic commented on rails/app/controllers/water_entries_controller.rb
> +    @recent_water_entries = recent_entries("water")
Where is this `recent_entries` method declared? I cannot find declaration of this method. This seems to not be fully implemented?

2024-02-28 20:41 UTC, vfonic commented on rails/app/controllers/water_entries_controller.rb
> +    task = params[:amount_unit]
`task` and `amount_unit` don't seem to depict the same thing. Is this the correct assignment? `task = params[:amount_unit]`

2024-03-29 12:49 UTC, closed without merging